import type { Machine, MachineCategory } from "./types";

/**
 * PLACEHOLDER-DATA. Mått, kapacitet och portar är branschgeneriska och ska
 * ersättas med INKAB:s verkliga maskindata innan verktyget visas för kund.
 * Priser ligger medvetet INTE här — se src/lib/server/pricebook.ts.
 */

const std = (lengthMm: number, widthMm: number, levelMm: number, allowsDirectionChange = false) => [
  {
    id: "in",
    role: "in" as const,
    pos: { x: 0, y: widthMm / 2 },
    dir: "x+" as const,
    levelMm,
    widthMm: [600, 2400] as [number, number],
    allowsDirectionChange,
  },
  {
    id: "out",
    role: "out" as const,
    pos: { x: lengthMm, y: widthMm / 2 },
    dir: "x+" as const,
    levelMm,
    widthMm: [600, 2400] as [number, number],
    allowsDirectionChange,
  },
];

export const MACHINES: Machine[] = [
  {
    id: "ib2",
    sku: "IB2-5500",
    name: "Inmatningsbord IB2",
    category: "infeed",
    summary: "Tar emot paket från råsorteringen och matar in dem i linjen.",
    footprint: { lengthMm: 5500, widthMm: 3800, heightMm: 1250 },
    ports: std(5500, 3800, 900, true),
    mirrorable: true,
    operatorPriority: 2,
    zones: [{ type: "service", box: { x: 0, y: -1200, l: 5500, w: 1200 }, label: "Service IB2" }],
    capacity: {
      packagesPerHour: 26,
      packageLengthMm: [2400, 6000],
      packageWidthMm: [800, 1300],
      packageHeightMm: [500, 1400],
      maxWeightKg: 3500,
    },
    utilities: { powerKw: 7.5, airNlPerMin: 0 },
    foundation: { pitDepthMm: 0, pointLoadKn: 42 },
    stepFile: "IB2-5500.step",
    leadTimeWeeks: 20,
    options: [{ id: "ib2-roll", name: "Rullbanepåbyggnad", deltaLengthMm: 1500, deltaPowerKw: 1.5 }],
  },
  {
    id: "tt1",
    sku: "TT1-4000",
    name: "Tvärtransportör TT1",
    category: "transport",
    summary: "Vinklar flödet 90°. Krävs när paketen kommer in från höger eller vänster.",
    footprint: { lengthMm: 4000, widthMm: 2600, heightMm: 1100 },
    ports: [
      {
        id: "in",
        role: "in",
        pos: { x: 0, y: 1300 },
        dir: "x+",
        levelMm: 900,
        widthMm: [600, 2400],
        allowsDirectionChange: true,
      },
      {
        id: "out",
        role: "out",
        pos: { x: 2000, y: 2600 },
        dir: "y+",
        levelMm: 900,
        widthMm: [600, 2400],
        allowsDirectionChange: true,
      },
    ],
    mirrorable: true,
    zones: [{ type: "service", box: { x: -1000, y: 0, l: 1000, w: 2600 }, label: "Service TT1" }],
    capacity: {
      packagesPerHour: 28,
      packageLengthMm: [2400, 6000],
      packageWidthMm: [800, 1300],
      packageHeightMm: [500, 1400],
      maxWeightKg: 3500,
    },
    utilities: { powerKw: 5.5, airNlPerMin: 0 },
    foundation: { pitDepthMm: 400, pointLoadKn: 30 },
    stepFile: "TT1-4000.step",
    leadTimeWeeks: 18,
    options: [],
  },
  {
    id: "pl3",
    sku: "PL3-STD",
    name: "Paketläggare PL3",
    category: "stacking",
    summary: "Bygger paket varvvis med sekundärhiss.",
    footprint: { lengthMm: 9200, widthMm: 5400, heightMm: 4600 },
    ports: std(9200, 5400, 900),
    mirrorable: true,
    operatorPriority: 4,
    zones: [
      { type: "service", box: { x: 0, y: -1400, l: 9200, w: 1400 }, label: "Service PL3" },
      { type: "safety", box: { x: -800, y: -800, l: 10800, w: 7000 }, label: "Skyddszon PL3" },
    ],
    capacity: {
      packagesPerHour: 24,
      packageLengthMm: [2400, 6000],
      packageWidthMm: [800, 1300],
      packageHeightMm: [500, 1400],
      maxWeightKg: 3500,
    },
    utilities: { powerKw: 26, airNlPerMin: 180 },
    foundation: { pitDepthMm: 900, pointLoadKn: 120 },
    stepFile: "PL3-STD.step",
    leadTimeWeeks: 30,
    options: [{ id: "pl3-servo", name: "Servotrim", deltaCapacity: 3, deltaPowerKw: 4 }],
  },
  {
    id: "ts4",
    sku: "TS4-STD",
    name: "Truckströläggare TS4",
    category: "stickers",
    summary: "Lägger truckströ mellan paketen. Kräver ströretur och magasin.",
    footprint: { lengthMm: 7500, widthMm: 6200, heightMm: 4100 },
    ports: std(7500, 6200, 900),
    mirrorable: true,
    operatorPriority: 5,
    zones: [
      { type: "service", box: { x: 0, y: -1500, l: 7500, w: 1500 }, label: "Service TS4" },
      { type: "safety", box: { x: -600, y: -600, l: 8700, w: 7400 }, label: "Skyddszon TS4" },
    ],
    capacity: {
      packagesPerHour: 22,
      packageLengthMm: [2400, 6000],
      packageWidthMm: [800, 1300],
      packageHeightMm: [500, 1400],
      maxWeightKg: 3200,
    },
    utilities: { powerKw: 18.5, airNlPerMin: 220 },
    foundation: { pitDepthMm: 600, pointLoadKn: 85 },
    requires: ["sr2", "sf3"],
    stepFile: "TS4-STD.step",
    leadTimeWeeks: 28,
    options: [
      { id: "ts4-fack", name: "Extra ströfack", deltaWidthMm: 900 },
      { id: "ts4-cam", name: "Kamerakontroll", deltaPowerKw: 0.5 },
    ],
  },
  {
    id: "sr2",
    sku: "SR2-STD",
    name: "Ströretur SR2",
    category: "stickers",
    summary: "Returnerar strö till magasinet efter torkning.",
    footprint: { lengthMm: 3200, widthMm: 2400, heightMm: 2200 },
    ports: std(3200, 2400, 900),
    mirrorable: true,
    operatorPriority: 1,
    zones: [{ type: "service", box: { x: 0, y: -1000, l: 3200, w: 1000 }, label: "Service SR2" }],
    capacity: {
      packagesPerHour: 30,
      packageLengthMm: [2400, 6000],
      packageWidthMm: [800, 1300],
      packageHeightMm: [500, 1400],
      maxWeightKg: 3500,
    },
    utilities: { powerKw: 4, airNlPerMin: 60 },
    foundation: { pitDepthMm: 0, pointLoadKn: 22 },
    stepFile: "SR2-STD.step",
    leadTimeWeeks: 16,
    options: [],
  },
  {
    id: "pp1",
    sku: "PP1-H",
    name: "Paketpress PP1",
    category: "processing",
    summary: "Pressar paketet inför bandning.",
    footprint: { lengthMm: 4800, widthMm: 3400, heightMm: 3200 },
    ports: std(4800, 3400, 900),
    mirrorable: true,
    operatorPriority: 2,
    zones: [{ type: "service", box: { x: 0, y: -1200, l: 4800, w: 1200 }, label: "Service PP1" }],
    capacity: {
      packagesPerHour: 18,
      packageLengthMm: [2400, 6000],
      packageWidthMm: [800, 1300],
      packageHeightMm: [500, 1400],
      maxWeightKg: 3500,
    },
    utilities: { powerKw: 22, airNlPerMin: 140 },
    foundation: { pitDepthMm: 400, pointLoadKn: 95 },
    stepFile: "PP1-H.step",
    leadTimeWeeks: 22,
    options: [],
  },
  {
    id: "bm2",
    sku: "BM2-STD",
    name: "Bandningsmaskin BM2",
    category: "finishing",
    summary: "Omsnörning med PET-band, två till fyra band per paket.",
    footprint: { lengthMm: 3600, widthMm: 3200, heightMm: 2800 },
    ports: std(3600, 3200, 900),
    mirrorable: true,
    operatorPriority: 3,
    zones: [{ type: "service", box: { x: 0, y: -1100, l: 3600, w: 1100 }, label: "Service BM2" }],
    capacity: {
      packagesPerHour: 20,
      packageLengthMm: [2400, 6000],
      packageWidthMm: [800, 1300],
      packageHeightMm: [500, 1400],
      maxWeightKg: 3500,
    },
    utilities: { powerKw: 9, airNlPerMin: 320 },
    foundation: { pitDepthMm: 0, pointLoadKn: 28 },
    stepFile: "BM2-STD.step",
    leadTimeWeeks: 18,
    options: [{ id: "bm2-4band", name: "Fyra band", deltaCapacity: -2 }],
  },
  {
    id: "pk1",
    sku: "PK1-STD",
    name: "Paketkap PK1",
    category: "processing",
    summary: "Kapar paketändarna till exakt längd.",
    footprint: { lengthMm: 5200, widthMm: 4200, heightMm: 3000 },
    ports: std(5200, 4200, 900),
    mirrorable: true,
    operatorPriority: 3,
    zones: [
      { type: "service", box: { x: 0, y: -1300, l: 5200, w: 1300 }, label: "Service PK1" },
      { type: "safety", box: { x: -500, y: -500, l: 6200, w: 5200 }, label: "Skyddszon PK1" },
    ],
    capacity: {
      packagesPerHour: 19,
      packageLengthMm: [2400, 6000],
      packageWidthMm: [800, 1300],
      packageHeightMm: [500, 1400],
      maxWeightKg: 3500,
    },
    utilities: { powerKw: 30, airNlPerMin: 260 },
    foundation: { pitDepthMm: 700, pointLoadKn: 110 },
    stepFile: "PK1-STD.step",
    leadTimeWeeks: 24,
    options: [],
  },
  {
    id: "kt",
    sku: "KT-VAR",
    name: "Kedjetransportör KT",
    category: "transport",
    summary: "Kedjetransportör med valfri längd. Används som buffert före utlastning.",
    footprint: { lengthMm: 12000, widthMm: 2200, heightMm: 900 },
    ports: std(12000, 2200, 900),
    mirrorable: false,
    parametricLength: { minMm: 3000, maxMm: 30000, pricePerMeter: 24000 },
    zones: [{ type: "service", box: { x: 0, y: -900, l: 12000, w: 900 }, label: "Service KT" }],
    capacity: {
      packagesPerHour: 34,
      packageLengthMm: [2400, 6000],
      packageWidthMm: [800, 1300],
      packageHeightMm: [500, 1400],
      maxWeightKg: 3500,
    },
    utilities: { powerKw: 5.5, airNlPerMin: 0 },
    foundation: { pitDepthMm: 0, pointLoadKn: 18 },
    stepFile: "KT-VAR.step",
    leadTimeWeeks: 14,
    options: [],
  },
  {
    id: "rb",
    sku: "RB-12000",
    name: "Rullbana RB",
    category: "transport",
    summary: "Drivna rullar för längsgående transport.",
    footprint: { lengthMm: 12000, widthMm: 1570, heightMm: 490 },
    ports: std(12000, 1570, 900),
    mirrorable: false,
    zones: [{ type: "service", box: { x: 0, y: -800, l: 12000, w: 800 }, label: "Service RB" }],
    capacity: {
      packagesPerHour: 32,
      packageLengthMm: [2400, 6000],
      packageWidthMm: [800, 1300],
      packageHeightMm: [500, 1400],
      maxWeightKg: 3000,
    },
    utilities: { powerKw: 4, airNlPerMin: 0 },
    foundation: { pitDepthMm: 0, pointLoadKn: 14 },
    stepFile: "RB-12000.step",
    leadTimeWeeks: 12,
    options: [],
  },
  {
    id: "ub1",
    sku: "UB1-STD",
    name: "Utlastningsbana UB1",
    category: "outfeed",
    summary: "Avlämningsbord där trucken hämtar färdiga paket.",
    footprint: { lengthMm: 6400, widthMm: 3000, heightMm: 800 },
    ports: std(6400, 3000, 900),
    mirrorable: true,
    operatorPriority: 1,
    zones: [{ type: "service", box: { x: 0, y: -900, l: 6400, w: 900 }, label: "Service UB1" }],
    capacity: {
      packagesPerHour: 30,
      packageLengthMm: [2400, 6000],
      packageWidthMm: [800, 1300],
      packageHeightMm: [500, 1400],
      maxWeightKg: 3500,
    },
    utilities: { powerKw: 3, airNlPerMin: 0 },
    foundation: { pitDepthMm: 0, pointLoadKn: 20 },
    stepFile: "UB1-STD.step",
    leadTimeWeeks: 14,
    options: [],
  },

  /* ── Hjälpobjekt: ingår inte i kedjan, placeras vid sin ankarmaskin ── */
  {
    id: "mp1",
    sku: "MP1-STD",
    name: "Manöverpulpet MP1",
    category: "control",
    summary: "Operatörens pulpet. Placeras på vald sida vid linjens mest manuella station.",
    aux: true,
    footprint: { lengthMm: 3400, widthMm: 1700, heightMm: 1200 },
    ports: [],
    mirrorable: false,
    zones: [{ type: "service", box: { x: -800, y: -800, l: 5000, w: 3300 }, label: "Operatörsyta" }],
    capacity: {
      packagesPerHour: 0,
      packageLengthMm: [0, 0],
      packageWidthMm: [0, 0],
      packageHeightMm: [0, 0],
      maxWeightKg: 0,
    },
    utilities: { powerKw: 0.5, airNlPerMin: 0 },
    foundation: { pitDepthMm: 0, pointLoadKn: 4 },
    stepFile: "MP1-STD.step",
    leadTimeWeeks: 10,
    options: [],
  },
  {
    id: "sf3",
    sku: "SF3-STD",
    name: "Ströfacksmagasin SF3",
    category: "stickers",
    summary: "Magasin för truckströ. Fylls av truck, placeras på vald sida.",
    aux: true,
    anchorFor: "ts4",
    footprint: { lengthMm: 5700, widthMm: 3000, heightMm: 2500 },
    ports: [],
    mirrorable: false,
    zones: [{ type: "service", box: { x: -600, y: -600, l: 6900, w: 4200 }, label: "Påfyllning SF3" }],
    capacity: {
      packagesPerHour: 0,
      packageLengthMm: [0, 0],
      packageWidthMm: [0, 0],
      packageHeightMm: [0, 0],
      maxWeightKg: 0,
    },
    utilities: { powerKw: 0, airNlPerMin: 0 },
    foundation: { pitDepthMm: 0, pointLoadKn: 12 },
    stepFile: "SF3-STD.step",
    leadTimeWeeks: 12,
    options: [],
  },
];

export const MACHINE_BY_ID = new Map(MACHINES.map((m) => [m.id, m]));

export function getMachine(id: string): Machine | undefined {
  return MACHINE_BY_ID.get(id);
}

export const CATEGORY_LABEL: Record<MachineCategory, string> = {
  infeed: "Inmatning",
  stacking: "Paketläggning",
  stickers: "Ströläggning",
  transport: "Transport",
  processing: "Bearbetning",
  finishing: "Finish",
  outfeed: "Utlastning",
  control: "Styr",
};

/** Rimlig ordning i kedjan; används för att varna om linjen är felsorterad. */
export const CATEGORY_ORDER: MachineCategory[] = [
  "infeed",
  "transport",
  "stacking",
  "stickers",
  "processing",
  "finishing",
  "outfeed",
  "control",
];
